import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";
import starlightSidebarTopics from "starlight-sidebar-topics";
import starlightLinksValidator from "starlight-links-validator";
import partytown from "@astrojs/partytown";
import vercel from "@astrojs/vercel";
import { setGlobalDispatcher, Agent } from "undici";

import redirects from "./src/redirects";
import { officialPluginsList } from "./src/content/officialPluginList";

// We set this up to prefer IPv4 connections to IPv6 connections
// as otherwise the Vercel deployments were failing when trying to access
// the Ghost API
setGlobalDispatcher(new Agent({ connect: { family: 4 } }));

export default defineConfig({
  site: "https://hardhat.org/",
  adapter: vercel({}),
  integrations: [
    starlight({
      title: "Hardhat 3",
      favicon: "/favicon.ico",
      disable404Route: true,
      logo: {
        light: "./src/assets/hardhat-logo-light.svg",
        dark: "./src/assets/hardhat-logo-dark.svg",
        replacesTitle: true,
      },
      editLink: {
        baseUrl:
          "https://github.com/NomicFoundation/hardhat-website/edit/main/",
      },
      head: [
        {
          tag: "meta",
          attrs: {
            property: "og:image",
            content: "/thumbnail.png",
          },
        },
      ],
      social: [
        {
          icon: "github",
          label: "GitHub",
          href: "https://github.com/NomicFoundation/hardhat",
        },
        {
          icon: "x.com",
          label: "X",
          href: "https://x.com/HardhatHQ",
        },
        {
          icon: "discord",
          label: "Discord",
          href: "https://hardhat.org/discord",
        },
      ],
      plugins: [
        starlightSidebarTopics(
          [
            {
              label: "Hardhat 3",
              id: "hardhat",
              link: "/docs/getting-started/",
              items: [
                {
                  slug: "docs/getting-started",
                },
                {
                  label: "Guides",
                  autogenerate: {
                    directory: "docs/guides",
                  },
                },
                {
                  label: "Hardhat 3",
                  autogenerate: {
                    directory: "docs/hardhat3",
                  },
                },
                {
                  label: "Reference",
                  autogenerate: {
                    directory: "docs/reference",
                  },
                },
                {
                  // /docs/plugins is a custom page, not generated by Starlight
                  // don't use slug here
                  label: "Plugins",
                  items: [
                    {
                      label: "Official plugins",
                      link: "/docs/plugins#_top",
                    },
                    {
                      label: "Community plugins",
                      link: "/docs/plugins#community-plugins",
                    },
                    {
                      label: "Plugin development docs",
                      link: "https://hardhat.org/docs/plugin-development",
                    },
                  ],
                },
                { slug: "hardhat2" },
              ],
            },
            {
              label: "Hardhat Ignition",
              id: "ignition",
              link: "/ignition/docs",
              items: [
                { slug: "ignition/docs/getting-started" },
                {
                  label: "Guides",
                  autogenerate: {
                    directory: "ignition/docs/guides",
                  },
                },
                {
                  label: "Reference",
                  autogenerate: {
                    directory: "ignition/docs/reference",
                  },
                },
                {
                  label: "Explanations",
                  autogenerate: {
                    directory: "ignition/docs/explanations",
                  },
                },
              ],
            },
            {
              label: "Migrate from Hardhat 2",
              id: "migrate-from-hardhat2",
              link: "/docs/migrate-from-hardhat2/",
              items: [
                {
                  slug: "docs/migrate-from-hardhat2",
                },
                {
                  label: "Guides",
                  autogenerate: {
                    directory: "/docs/migrate-from-hardhat2/guides",
                  },
                },
              ],
            },
            {
              label: "Plugin development",
              id: "plugin-development",
              link: "/docs/plugin-development/",
              items: [
                { slug: "docs/plugin-development" },
                {
                  label: "Tutorial",
                  autogenerate: {
                    directory: "docs/plugin-development/tutorial",
                  },
                },
                {
                  label: "Guides",
                  autogenerate: {
                    directory: "docs/plugin-development/guides",
                  },
                },
                {
                  label: "Reference",
                  autogenerate: {
                    directory: "docs/plugin-development/reference",
                  },
                },
                {
                  label: "Explanations",
                  autogenerate: {
                    directory: "docs/plugin-development/explanations",
                  },
                },
              ],
            },
          ],
          {
            topics: {
              hardhat: ["/docs/plugins", "/docs/plugins/*"],
            },
          },
        ),
        starlightLinksValidator({
          exclude: Object.keys(redirects).concat(
            officialPluginsList.map((p) => `/docs/plugins/${p.slug}`),
          ),
        }),
      ],
      customCss: ["./src/styles/custom-starlight-theme.css"],
      components: {
        Sidebar: "./src/components/starlight-overrides/Sidebar.astro",
        Header: "./src/components/starlight-overrides/Header.astro",
      },
    }),
    partytown({
      config: {
        forward: ["dataLayer.push"],
      },
    }),
  ],
  trailingSlash: "never",
  redirects,
  vite: {
    server: {
      watch: {
        ignored: ["**/.vercel/**", "**/.vscode/**"],
      },
    },
  },
});
