// Sidebar topic definitions shared between astro.config.ts and llms.txt generation.

import type {
  StarlightSidebarTopicsUserConfig,
  StarlightSidebarTopicsUserOptions,
} from "starlight-sidebar-topics";

import fs from "fs";
import path from "path";

// We manually generate the list of directories of the cheatcodes folder, so
// that we can control the order of the documents listed at the same level.
// Otherwise they'll be shown at the top, and the folders later.
const cheatchodesDirectories = fs
  .globSync(
    path.join(import.meta.dirname, "content/docs/docs/reference/cheatcodes/*"),
  )
  .filter((file) => fs.statSync(file).isDirectory())
  .sort()
  .map((file) => ({
    label: path.basename(file),
    autogenerate: {
      directory: path.relative(
        path.join(import.meta.dirname, "content/docs"),
        file,
      ),
    },
    collapsed: true,
  }));

export const sidebarTopics: StarlightSidebarTopicsUserConfig = [
  {
    label: "Hardhat 3",
    id: "hardhat",
    link: "/docs/getting-started/",
    items: [
      {
        slug: "docs/getting-started",
      },
      {
        label: "Hardhat 3",
        autogenerate: {
          directory: "docs/hardhat3",
        },
      },
      {
        label: "Tutorial",
        collapsed: true,
        autogenerate: {
          directory: "docs/tutorial",
        },
      },
      {
        label: "Guides",
        items: [
          {
            label: "Writing Smart contracts",
            collapsed: true,
            autogenerate: {
              directory: "docs/guides/writing-contracts",
            },
          },
          {
            label: "Testing Smart contracts",
            collapsed: true,
            autogenerate: {
              directory: "docs/guides/testing",
            },
          },
          {
            label: "Deploying Smart contracts",
            collapsed: true,
            autogenerate: {
              directory: "docs/guides/deployment",
            },
          },
          { slug: "docs/guides/smart-contract-verification" },
          { slug: "docs/guides/configuration-variables" },
          { slug: "docs/guides/writing-tasks" },
          { slug: "docs/guides/writing-scripts" },
          { slug: "docs/guides/execution-traces" },
          { slug: "docs/guides/forking" },
          { slug: "docs/guides/hardhat-node" },
          { slug: "docs/guides/hardhat-console" },
          // { slug: "docs/guides/command-line-completion" },
          { slug: "docs/guides/getting-help" },
        ],
      },
      {
        label: "Cookbook",
        collapsed: true,
        autogenerate: {
          directory: "docs/cookbook",
        },
      },
      {
        label: "Reference",
        collapsed: true,
        items: [
          { slug: "docs/reference/configuration" },
          { slug: "docs/reference/network-manager" },
          { slug: "docs/reference/edr-simulated-networks" },
          { slug: "docs/reference/op-stack-support" },
          { slug: "docs/reference/json-rpc-methods" },
          { slug: "docs/reference/artifacts" },
          { slug: "docs/reference/console-log" },
          { slug: "docs/reference/foundry-compatibility" },
          {
            label: "Solidity test cheatcodes",
            collapsed: true,
            items: [
              { slug: "docs/reference/cheatcodes/cheatcodes-overview" },
              ...cheatchodesDirectories,
              { slug: "docs/reference/cheatcodes/unsupported-cheatcodes" },
            ],
          },
          { slug: "docs/reference/stability-guarantees" },
          { slug: "docs/reference/nodejs-support" },
          { slug: "docs/reference/errors" },
        ],
      },
      {
        label: "Explanations",
        collapsed: true,
        autogenerate: {
          directory: "docs/explanations",
        },
      },
      {
        // /docs/plugins is a custom page, not generated by Starlight
        // don't use slug here
        label: "Plugins",
        items: [
          {
            label: "Official plugins",
            link: "/docs/plugins/official-plugins",
          },
          {
            label: "Community plugins",
            link: "/docs/plugins/community-plugins",
          },
          {
            label: "Plugin development docs",
            // We have to use the full URL here because this is
            // treated as a link to a different sidebar topic
            link: "https://hardhat.org/docs/plugin-development",
          },
        ],
      },
      { slug: "hardhat2" },
    ],
  },
  {
    label: "Hardhat Ignition",
    id: "ignition",
    link: "/ignition/docs",
    items: [
      { slug: "ignition/docs/getting-started" },
      {
        label: "Guides",
        autogenerate: {
          directory: "ignition/docs/guides",
        },
      },
      {
        label: "Reference",
        autogenerate: {
          directory: "ignition/docs/reference",
        },
      },
      {
        label: "Explanations",
        autogenerate: {
          directory: "ignition/docs/explanations",
        },
      },
    ],
  },
  {
    label: "Migrate from Hardhat 2",
    id: "migrate-from-hardhat2",
    link: "/docs/migrate-from-hardhat2/",
    items: [
      {
        slug: "docs/migrate-from-hardhat2",
      },
      {
        label: "Guides",
        autogenerate: {
          directory: "/docs/migrate-from-hardhat2/guides",
        },
      },
    ],
  },
  {
    label: "Plugin development",
    id: "plugin-development",
    link: "/docs/plugin-development/",
    items: [
      { slug: "docs/plugin-development" },
      {
        label: "Tutorial",
        autogenerate: {
          directory: "docs/plugin-development/tutorial",
        },
      },
      {
        label: "Guides",
        autogenerate: {
          directory: "docs/plugin-development/guides",
        },
      },
      {
        label: "Reference",
        autogenerate: {
          directory: "docs/plugin-development/reference",
        },
      },
      {
        label: "Explanations",
        autogenerate: {
          directory: "docs/plugin-development/explanations",
        },
      },
    ],
  },
];

export const sidebarTopicOptions: StarlightSidebarTopicsUserOptions = {
  topics: {
    hardhat: [
      "/docs/plugins/official-plugins",
      "/docs/plugins/community-plugins",
      "/docs/plugins/*",
    ],
  },
  exclude: ["/hardhat-vscode"],
};
